"""weko's user update

Revision ID: 748b64e82832
Revises: 9cc5a441b613
Create Date: 2025-09-08 13:07:51.893392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748b64e82832'
down_revision = '9cc5a441b613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
