services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: banking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-banking}
      POSTGRES_USER: ${DB_USER:-bankuser}
      POSTGRES_PASSWORD: ${DB_PASS:-securepassword123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - banking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-bankuser} -d ${DB_NAME:-banking}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Flask Banking Application
  banking-app:
    build: .
    container_name: banking-app
    restart: unless-stopped
    environment:
      # Database Configuration
      DATABASE_TYPE: postgresql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-banking}
      DB_USER: ${DB_USER:-bankuser}
      DB_PASS: ${DB_PASS:-securepassword123}
      
      # Flask Configuration
      SECRET_KEY: ${SECRET_KEY:-your-super-secret-key-change-in-production}
      FLASK_ENV: ${FLASK_ENV:-production}
      DEBUG: ${DEBUG:-False}
      
      # Security Configuration
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE:-True}
      LOCAL_TEST: ${LOCAL_TEST:-False}
      
      # Application Configuration
      BANK_NAME: ${BANK_NAME:-Kerata-Zemke}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - banking-network
    volumes:
      - ./logs:/app/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: banking-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - banking-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  banking-network:
    driver: bridge